name: Automated Training

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn tensorflow

      - name: Run training script
        run: python scripts/train.py
